version: v2

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable:
    - errcheck # Disabling per your project requirements
  enable:
    - ineffassign
    - staticcheck
    - unused
    - gofumpt

issues:
  # The 'exclude-rules' must be a list under 'issues'
  exclude-rules:
    # 1. ineffassign: renderer.go
    - path: internal/render/chrome/renderer.go
      linters:
        - ineffassign
      text: "ineffectual assignment to err"

    # 2. staticcheck: config_test.go (S1009 - redundant nil check)
    - path: internal/common/config/config_test.go
      linters:
        - staticcheck
      text: "S1009"

    # 3. staticcheck: request_helpers.go (SA1019 - deprecated VisitAll)
    - path: internal/edge/server/request_helpers.go
      linters:
        - staticcheck
      text: "SA1019"

    # 4. staticcheck: validator_test.go (S1011 - loop to append)
    - path: internal/edge/validate/validator_test.go
      linters:
        - staticcheck
      text: "S1011"

    # 5. unused: specific functions in expansion and formatter
    - path: internal/common/config/alias_expansion.go
      linters:
        - unused
    - path: internal/edge/events/formatter.go
      linters:
        - unused

  # This ensures we don't hide issues that are actually important
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
